version: '3.1'

services:

  proxy:
    container_name: nginx_proxy
    image: nginx:latest # this will use the latest version of 1.11.x
    ports:
      - 80:80 # expose 80 on host and sent to 80 in container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/html:/var/www/html
      - /etc/hosts:/etc/hosts
      #- ./nginx/index.php:/var/www/html/index.php
    links:
      - apache2:apache2
      - db:db
    depends_on:
      - apache2
#    networks:
#      - frontend


  apache2:
    container_name: apache2
    build: .
    volumes:
      - ./apache2/ports.conf:/etc/apache2/ports.conf
      - ./apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./nginx/html/:/var/www/html/
    links:
      - db:db
    depends_on:
      - db
#    networks:
#      - frontend
#      - backend

# Use root/example as user/password credentials


  db:
    image: mariadb:latest
    container_name: mariadb
    #restart: always
    environment:
      #MYSQL_DATABASE: publications
      #MYSQL_USER: root
      #MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
      #MYSQL_ROOT_HOST: apache2
    #command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql/:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf

  adminer:
    image: adminer
    ports:
      - 8080:8080



#networks:
#  frontend:
#  backend: